#!/usr/bin/env  bash
# File: 	edit
# Description:	
# GNU General Public License (GPL) 2016 by Simon Arjuna Erat (sea) (erat.simon æ gmail,com)
# ------------------------------------------------------
#
#	Variables
#
	
#
#	Functions
#
	
#
#	Action & Display
#
	
